version: '3'

services: 
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 128.199.105.69
      KAFKA_ADVERTISED_PORT: 9091
      KAFKA_LISTENERS: PLAINTEXT://:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://128.199.105.69:9091
      KAFKA_ZOOKEEPER_CONNECT: 128.199.105.69:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
