version: '3'

services:
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 128.199.105.69
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://128.199.105.69:9092
      KAFKA_ZOOKEEPER_CONNECT: 128.199.105.69:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
